spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:${DB_PORT:5432}/${DB_NAME:diagnostic_ai}}
    username: ${DB_USER:diagnostic}
    password: ${DB_PASSWORD:diagnostic}
